api_platform:
    title: 'Powerful API'
    description: 'A powerful _and simple_ API implemented by <a href="https://www.linkedin.com/in/rezehnde/">Rezende</a> with Symfony and API Platform'
    version: '0.0.1'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
